### ISSUE TITLE
latest conda packages generated inconsistent venn and upset plots

### ISSUE THREAD

**Issue by sclan** [wdecoster/surpyvor#10]
Environment: SURVIVOR and miniconda surpyvor package on ubuntu 16.04
I had several paired comparison and the upset plot showed no intersect/overlap variants while there is a lot of overlapped variants in the venn diagram output. 

In this case, the upset plot seems to be correct because the independent R plot generates the venn diagram without intersect (which agrees with the upset plot).

I checked the https://github.com/wdecoster/surpyvor/blob/master/surpyvor/parse_arguments.py
and did not find anything out of ordinary in terms of parameters used by both plots.

**Comment by wdecoster** [comment]
Is this a dataset you can share for me to reproduce this issue?

**Comment by wdecoster** [comment]
Do you have any follow up on this?
