### ISSUE TITLE
missing options for highsens and highconf

### ISSUE THREAD

**Issue by sclan** [wdecoster/surpyvor#11]
One thing I am not clear about is why the -d (max distance), -c (min number of callers) and --minlength (min SV length) options are not offered for `surpyvor highsens` and `surpyvor highconf` to calculate the union and intersect variants among input VCFs?

My understanding is they are both based on the merged vcfs so if the above settings are not offered, the default setting from parse_arguments.py will be used and that will be different from the merged VCF output using `surpyvor merge` command with customized argument values.

**Comment by wdecoster** [comment]
Yes you are absolutely right on this. And it would be equally possible to offer these options for highsens and highconf, but I've always stuck to the default. If you want I can, of course, add those options.

**Comment by sclan** [comment]
Thanks that would be extremely helpful. My study is to compare SVs with various distance of the breakpoint starting/stoping between samples. We expect to have greater intersect, when the distance is 0 (exact match of breakpoints) between VCFs called by one SV caller, but a lot less intersect from the two VCFs called by different tools with the exact breakpoint match. It would be useful to back that up with surpyvor.

**Comment by wdecoster** [comment]
I don't have a lot of time, but I've quickly added  -d (max distance) and --minlength to highsens and highconf. I hope I didn't make any mistake :) It's available in surpyvor 0.8.1.

I don't think it makes sense to add `-c` as for highconf this is the number of input variants (all calls must support a variant) and for highsens this is 1 (any caller is enough). Or do you disagree?

**Comment by sclan** [comment]
I totally agree. It works for most of the situation to find the intersect. Though in some unique situations, people may wish to perform some sort of qc by making sure that there are at least certain percentage of variants picked up by more than one caller. 

If there are three input VCFs each are called by different caller, the intersect/overlap from at least 2 callers will be a subset of variants from being called by least one caller (all variants). 

Having the full set of options also provides consistent user expectations when they run the sub commands.
