### ISSUE TITLE
SURVIVOR update

### ISSUE THREAD

**Issue by cccnrc** [wdecoster/surpyvor#13]
Hey @wdecoster, SURVIVOR has been updated due to a issue I found ([link here](https://github.com/fritzsedlazeck/SURVIVOR/issues/134)). I think you need to update the SURVIVOR version that is included in surpyvor. I had moved the new SURVIVOR executable to `/home/enrico/miniconda3/envs/surpyvor/bin` and it works now.

**Comment by wdecoster** [comment]
There is no SURVIVOR packaged together with surpyvor, surpyvor just expects it is installed. The best would be to update the SURVIVOR version on bioconda. The way you fixed it on your system also works, of course ;)
