### ISSUE TITLE
Conda UnsatisfiableError: The following specifications were found to be incompatible with each other

### ISSUE THREAD

**Issue by lentil824** [wdecoster/surpyvor#14]
Hi,
I am having issues with the installation of this package using "conda install -c bioconda surpyvor"
The error message is:
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions
I used conda installed pbsv, and svim (created new environment for svim as recommended) , no issues at all. 
I also tried to install surpyvor by creating a new environment "conda create -n surpyvor_env --channel bioconda surpyvor", the same error message again. Could you help on this?

Thanks,
Susan

**Comment by lentil824** [comment]
Hi, 
I also put the bcftools (version 1.12), htslib (version 1.12), SURVIVOR into the PATH, installed all required modules for python 3.7 (python version  I have: numpy 1.18, cyvcf2 0.30.4, matplotlib 3.2.1, matplotlib-venn 0.11.6, upsetplot 0.4.1) . Still the same error message. The detailed log showed below after conda install:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.                           failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions

I need some help to know which package caused the conflict. 
Thanks,
Susan

**Comment by wdecoster** [comment]
Could you please try again with `mamba`? [Mamba](https://github.com/mamba-org/mamba) is a drop-in replacement for conda, usually faster and better at resolving these conflicts.

You can install mamba with conda itself: `conda install mamba` and from then on you can use `mamba` instead of `conda`, e.g. `mamba create -n surpyvor_env --channel bioconda surpyvor`.

Also make sure you have configured the channels appropriately for bioconda (see the [documentation](https://bioconda.github.io/user/install.html#set-up-channels)).

**Comment by lentil824** [comment]
Thank you for the suggestion! I added the channel conda-forge, installed Mamba through conda-forge, then used mamba to install surpyvor. It is good now. Thank you!

**Comment by agolicz** [comment]
Hi,
I am encountering a similar issue with both conda and mamba. Mamba gives the following:

Mamba gives this:
bioconda/linux-64        Using cache
bioconda/noarch          Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
Encountered problems while solving:
  - nothing provides matplotlib-venn needed by surpyvor-0.5.0-py_0
