### ISSUE TITLE
Difference in common variants in Venn diagram

### ISSUE THREAD

**Issue by prasundutta87** [wdecoster/surpyvor#15]
Hi Wouter,

I have been playing around with surpyvor and its indeed a great tool for producing quick plots from SV VCF files. I had a small query. I was working towards comparing some of my SV VCF files to check how sequencing depth influenses number of SVs called. The first venn compares VCFs called from samples of similar depth and the second venn diagram compares it with another VCF file which has SVs called from a higher depth sample.

![image](https://user-images.githubusercontent.com/25484608/120939419-e546ee80-c70f-11eb-8182-d82237130e56.png)

![image](https://user-images.githubusercontent.com/25484608/120939422-e9730c00-c70f-11eb-9277-81a4c8436373.png)

All VCF files are actually consensus sets of PRECISE variants called using cuteSV and sniffles. So, each VCF file technically contains two samples.

My question is regarding the difference in common variants specifically between sample_3 and sample_4_SS in the two venn diagrams (3976 vs 3958). Could you let me know what could be the issue here?

Commands used:

surpyvor venn --variants sample_3_Survivor_merged.vcf sample_4_SS_Survivor_merged.vcf --names sample_3 sample_4_SS -d 1000 --minlength 30 --plotout sample_3_4_SS

surpyvor venn --variants sample_3_Survivor_merged.vcf sample_4_SS_Survivor_merged.vcf sample_2_merged_Survivor_merged_from_merged_BAM.vcf --names sample_3 sample_4_SS sample_3_4_SS_merged -d 1000 --minlength 30 --plotout sample_3_4_SS_merged

Software Version: surpyvor: 0.8.1, SURVIVOR 1.0.7

**Comment by wdecoster** [comment]
Hi,

My guess would be that by adding another variant set (sample_3_4_SS_merged) different combinations of variants are merged that are in close proximity (specified by `--minlength`). To debug this further you could rerun the surpyvor venn commands with `--keepmerged merged-variants.vcf` to save the data that the venn plot uses to a vcf file (and then check the overlapping variants).

Hope that helps,
Wouter

**Comment by prasundutta87** [comment]
Thanks a lot for this wdecoster. I was just wondering how deletion lengths are considered while drawing the SV length plots. I believe they are turned into absolute values and then plotted, right?

**Comment by wdecoster** [comment]
That's right - absolute values are used for all types.
