### ISSUE TITLE
about  surpyvor highconf

### ISSUE THREAD

**Issue by prasundutta87** [wdecoster/surpyvor#17]
Hi,

I observed that surpyvor highconf that technically mimics surpyvor merge (with the option SV calls should be supported by all callers) does not take strand into account and the options to change that, is not present in surpyvor highconf.

I tested the above statement using SURVIVOR merge where I put the option of "They should agree on strand" to no.

Can the strand option be added to surpyvor highconf or has it not been put due to some reason?

Regards,
Prasun

**Comment by wdecoster** [comment]
Hi Prasun,

Thanks or the suggestion, I'll try to add it soon.

Cheers,
Wouter

**Comment by prasundutta87** [comment]
Thanks a lot @wdecoster !!

**Comment by wdecoster** [comment]
Surpyvor v0.10.0 now has a `--strand` flag for highconf. Please let me know if you have other suggestions or feedback.

Best,
Wouter

**Comment by prasundutta87** [comment]
Thanks a lot for this quick action! :-)
