### ISSUE TITLE
extracting variants list unique to a specific group

### ISSUE THREAD

**Issue by dKlee99** [wdecoster/surpyvor#18]
Hi, thanks for providing this wonderful packages!! 

Is it possible to extract 99 variants list (in vcf/bed or any possible forms) that is only present in T15_kmers as well as the type of SV (INS, DEL, INV etc) there are?

Thank you very much for your help in advance !
DK
![image](https://user-images.githubusercontent.com/82995207/133436010-fd23e87d-cbf8-4253-92d6-59aad60ed86d.png)

**Comment by wdecoster** [comment]
Hi DK,

Thanks for your question. Yes, that should be possible, although not immediately using a surpyvor command. You could use either --keepmerged with `surpyvor venn` to save the merged VCF when creating the plot, or just use `surpyvor merge` to merge the datasets. You can then query the VCF using e.g. the SUPP_VECTOR or a bcftools command to extract those variants that fit your condition.

Cheers,
Wouter

**Comment by dKlee99** [comment]
Hi,
Thank you so much for your reply! 

Would it be possible to filter out by setting genotype of normal and T15 to ./. and 0/0 to see only T15_kmers (**somatic variations**) as well? I couldn't really understand the part "SUPP_VECTOR or a bcftools command to extract those variants that fit your condition." Thank you so much!

Kind regards,
DK

**Comment by dKlee99** [comment]
> Hi DK,
> 
> Thanks for your question. Yes, that should be possible, although not immediately using a surpyvor command. You could use either --keepmerged with `surpyvor venn` to save the merged VCF when creating the plot, or just use `surpyvor merge` to merge the datasets. You can then query the VCF using e.g. the SUPP_VECTOR or a bcftools command to extract those variants that fit your condition.
> 
> Cheers,
> Wouter

Did you mean use bcftools to filter out SV that is present in other two groups by genotype?

**Comment by wdecoster** [comment]
That should work yes, from the merged VCF.

**Comment by dKlee99** [comment]
Thank you very much!
