### ISSUE TITLE
Dependencies and usage

### ISSUE THREAD

**Issue by Nazeeefa** [wdecoster/surpyvor#2]
Hi Wouter,

Just a suggestion (may not be necessary) - it may be a good idea to mention dependencies it requires for installation.

Also, it would be helpful if there were few examples on how optional arguments can be used.

Again, just suggestions - let me know if I (as a user) can be of any help. 

Thank you for your work. I appreciate it.

Cheers,

Nazeefa

**Comment by wdecoster** [comment]
Hi Nazeeefa,

You are absolutely right. I'll probably improve the documentation early next week.
I was also planning to add this to bioconda. That shouldn't be too hard, as its dependencies already are available there.

Thanks for the suggestion, I appreciate all feedback!

Cheers,
Wouter

**Comment by Nazeeefa** [comment]
Great! Thank you! I look forward to it!
I really appreciate your time.

**Comment by wdecoster** [comment]
Things are taking a bit longer than I anticipated (e.g. https://github.com/conda-forge/staged-recipes/pull/8698/) but I did not forget this.

**Comment by Nazeeefa** [comment]
Hi Wouter,

No worries :) I understand, take your time - there's no rush.
If I have specific questions, I'll let you know. Thanks again for all the work and your time!

Cheers,
Nazeefa

**Comment by wdecoster** [comment]
Thanks for your patience. I have updated the documentation with regard to dependencies, installation and usage instructions.
Please let me know if anything is unclear or you can open a pull request to fix it ;-)

If there is something with SV vcf files that you would like to add, feel free to contribute or make suggestions.
