### ISSUE TITLE
surpyvor for SNPs

### ISSUE THREAD

**Issue by sonalhenson** [wdecoster/surpyvor#22]
Great tool Wouter. Do you plan on adding support for SNPs? I'd like to make an UpSet plot of SNPs. Thanks.

**Comment by wdecoster** [comment]
Hi,

That should be possible. I assume you have a merged vcf file? Or would you start from two VCFs?

Wouter

**Comment by sonalhenson** [comment]
Thanks for the speedy reply. 

I have both, individual VCFs and merged (using bcftools). When I use either (example command given below) I get the below error message. These VCFs have been filtered to remove indels. Unfiltered files work no problem. Looking at the tmp files created I see tmp VCFs for each sample, but the merged VCF (when individual files are used as input) has nothing but the header. It appears that the SURVIVOR merge command is failing (tested independently).

Do you have any insights on how to troubleshoot this error? 

surpyvor: 0.14.0, SURVIVOR 1.0.7 (installed via conda)
command: surpyvor upset --variants vcf1.vcf.gz vcf2.vcf.gz vcf3.vcf.gz vcf4.vcf.gz --names s1 s2 s3 s4 --plotout upsetplot.png 

Executing SURVIVOR...DONE
Writing to /tmp/bcftools.XTtO5T
Merging 0 temporary files
Cleaning
Done
Traceback (most recent call last):
  File "/XXX/XXX/miniconda3/envs/surpyvor/bin/surpyvor", line 10, in <module>
    sys.exit(main())
  File "/XXX/XXX/miniconda3/envs/surpyvor/lib/python3.10/site-packages/surpyvor/surpyvor.py", line 47, in main
    upset(args)
  File "/XXX/XXX/miniconda3/envs/surpyvor/lib/python3.10/site-packages/surpyvor/surpyvor.py", line 181, in upset
    upsets = utils.make_sets(vcf=vcf_out, names=args.names or args.variants)
  File "/XXX/XXX/miniconda3/envs/surpyvor/lib/python3.10/site-packages/surpyvor/utils.py", line 76, in make_sets
    tf_array = [[True, False]] * len(list(calls.keys())[0])
IndexError: list index out of range

Thanks

Edit: Also, running surpyvor merge and SURVIVOR merge command it calls independently give a vcf file with only header.

**Comment by wdecoster** [comment]
Yes, all merging in surpyvor is handled by SURVIVOR, which is specific for SVs and may just discard SNVs. So I guess that explains what you see. I will probably add a `--snv` flag, to make sure bcftools gets used for merging. That should solve things.

**Comment by wdecoster** [comment]
I have an untested v1.15 now, which is available through pip (and soon through conda) that has a `--snv` flag. Happy to troubleshoot if necessary, but I won't have time this week for testing :)
