### ISSUE TITLE
surpyvor prf

### ISSUE THREAD

**Issue by Nazeeefa** [wdecoster/surpyvor#5]
Hi Wouter,

I am trying to figure how prf sub-command works. I did a test run with `surpyvor prf --truth truth_set.vcf--test file1.vcf --test file2.vcf --bar`

**Output I received:**
```
Executing SURVIVOR...DONE
Writing to /tmp/bcftools-sort.3yt2Bq
Merging 1 temporary files
Cleaning
Done
Precision: 0.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/surpyvor", line 11, in <module>
    load_entry_point('surpyvor==0.5.0', 'console_scripts', 'surpyvor')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/surpyvor-0.5.0-py3.7.egg/surpyvor/surpyvor.py", line 40, in main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/surpyvor-0.5.0-py3.7.egg/surpyvor/surpyvor.py", line 105, in precision_recall_fmeasure
ZeroDivisionError: division by zero

```
Also, I am wondering whether the output of surpyvor prf reflects results of merged vcf file (created by survivor)? I have information about overlapping SVs (from merged vcf) and I'd like to assess precision-recall comparison of sets merged with truth set. Sorry if my question sounds a bit confusing, I do not know how this works.

I appreciate your advice on how to figure this out so I can run this properly. Thank you, I appreciate your time.

**Comment by wdecoster** [comment]
Hi Nazeeefa,

To be honest I'm quite surprised you got this far, as you specified --test twice. That's not the intended usage.
The script uses SURVIVOR merge to combine the test and the truth, and will then count true positives, false positives, etc, and give you precision, recall and F1 score.

Does that make sense?

Wouter

**Comment by Nazeeefa** [comment]
Hi Wouter,

Thank you for a quick reply. That makes sense, great! glad to know I was thinking along the right lines :smiley_cat: 

You are right about intended usage. I use at least 2 (and sometimes >2) test files when I run `merge` command of survivor so I wanted to remain consistent when it comes to `prf` measurement. I get the same output when I run `prf` with one test file, and it creates venn diagram instead of bar chart or matrix (I tested both).

Cheers,
Nazeefa

**Comment by wdecoster** [comment]
Hi Nazeefa,

Ah, alright then, good to hear. Does this answer the question then?

Thanks,
Wouter

**Comment by Nazeeefa** [comment]
Hi Wouter,

Sort of. Do you have any advice on how I can resolve the error that I shared above and mentioned just now? Thank you, I appreciate your time.

**Comment by wdecoster** [comment]
You also get it when you use only one --test? Do both VCFs contain genotypes or perhaps just calls?

**Comment by Nazeeefa** [comment]
Yes and, you can have a look at the test and truth set VCF files (posted in previous issue) https://github.com/wdecoster/surpyvor/issues/3#issuecomment-511198507

**Comment by wdecoster** [comment]
If that's again the truth set you are using I'll give you the same comment as in that previous issue:

> I'm quite sure the cause is that your truth set does not contain genotypes (0/0 ; 0/1 ; 1/1), but is a "position vcf". I suppose you could fix/fool the issue by adding GT 0/1 genotypes to a FORMAT column and SAMPLE column. Some sed would probably do the job, or any other scripting language.

**Comment by Nazeeefa** [comment]
Yes, that worked. Thank you for reminding :) I understand surpyvor is going to be updated to use latest release of SURVIVOR (https://github.com/wdecoster/surpyvor/issues/6#issuecomment-597559484), so I'll have another go to see how results from `prf` command looks.

Thank you for your time!
