### ISSUE TITLE
"Incompatibility" between surpyvor upset and GATK 4 Germline CNV caller data

### ISSUE THREAD

**Issue by Tintest** [wdecoster/surpyvor#8]
I'm having some issues with```surpyvor upset```. I'm trying to process .vcf from GATK4 germline CNV caller, but their format is a bit weird. I modified it a bit and added some information to this .vcf, but I still can't use surpyvor upset.

I manage to get an upset plot with data from tools like sniffles, pbsv and svim, it works. But it does not with data from GATk 4 CNV caller. So it must be "tool related". I hope you could tell me what in GATK4 .vcf files make it not work. 

I tried several commands, but to summerize with the one I would like to use :

```
 surpyvor upset -i -d 2000 --minlength 0 --variants NIST002A1_S1_40.vcf.gz NIST002A2_S1_40.vcf.gz --names NIST002A1 NIST002A2
Executing SURVIVOR...DONE
Writing to /tmp/bcftools-sort.fU9PoX
Merging 1 temporary files
Cleaning
Done
/home/tintest/miniconda3/lib/python3.7/site-packages/upsetplot/plotting.py:535: UserWarning: Attempting to set identical left == right == 0 results in singular transformations; automatically expanding.
  orig_ax.set_xlim(max_total, 0)
```

I tried to use ```surpyvor upset``` on the 2 identical .vcf files, with the same 3 variants but different sample names. The upset plot is blank. No intersection between both datasets (it should be 100% intersection). The warning seems to be related to the fact that the upset plot is blank.

Here is the exemple dataset and the generated blank upset plot :

https://filesender.renater.fr/?s=download&token=a1dea157-3bcd-8f27-2818-b82ebcdae8e2

Can you help me ?

Regards

**Comment by wdecoster** [comment]
It's a weird VCF indeed. But I'm afraid I have to tag @fritzsedlazeck here again, as I believe this to originate from SURVIVOR. The upset subcommand has a --keepmerged option, which will show you that the merged file only contains ./. genotypes.  I have added the merged file here:

[merged.vcf.txt](https://github.com/wdecoster/surpyvor/files/4330965/merged.vcf.txt)

@fritz: SURVIVOR merge samplefile 2000 1 -1 -1 -1 0 variants.vcf, using the VCF files linked by OP produces the merged VCF file from this post...

**Comment by fritzsedlazeck** [comment]
I dont get the question. What is the output with the GATK CNV caller?

**Comment by fritzsedlazeck** [comment]
Or do you mean the two types in the type coloumn?

**Comment by Tintest** [comment]
> 
> 
> I dont get the question. What is the output with the GATK CNV caller?

GATK4 Germline CNV caller output two kind of vcf files, intervals files and segments files (with contiguous intervals merged, that's the ones I gave you). I added in the INFO column, SVLEN and SVTYPE which are required by several tools to work (like truvari). I can give you originals .vcf files if you want.

I tried to execute ```surpyvor upset``` on several datasets from different tools, it works with all of them, except data from GATK4.

> 
> 
> Or do you mean the two types in the type coloumn?

I tried to modify that, but it still doesn't work with only one type displayed. Both < DEL >,< DUP > are displayed to every line, for every variant. GT:1 means DEL and GT:2 means DUP. There is also GT:0 but I removed them because they are uninformative. 

Regards.

**Comment by fritzsedlazeck** [comment]
yes can you share that VCF file? or a part of it

**Comment by fritzsedlazeck** [comment]
VCF files are standardized but the standard allows for quite some flexibility... so that is probably the problem. I have tested and adjusted the parser for SURVIVOR to many tools but never looked at GATK CNV caller.

**Comment by Tintest** [comment]
Here is a link with files to help you : 

https://filesender.renater.fr/?s=download&token=4b5bd78f-20ed-3e97-f7c3-b5360b928e5b

NIST002A_S1.vcf is a subsample of raw .vcf file outputed by GATK4 Germline CNV caller and  NIST002A_S1_modified.vcf is the same file with SVLEN and SVTYPE added by me.

Regards.

**Comment by fritzsedlazeck** [comment]
Thanks just looking at this. I will not incorporate that in SURVIVOR since it does not follow a classical SV vcf. What you need to do is: 
1. Change GT to 1/1 or 0/0. 0 or 1 or so is not parsable / understandable. Usually, that should be if an allele is het or hom but not what type.

2. Replace the type with DEL or DUP not DIPL. Also please delete the one or the other in the type column.

I dont necessarily need the SVLEN.  

 i hope that helps. I hope you can understand that I will not incorporate that format directly. I would reach out to the GATK CNV caller people and ask for a general VCF file. SNV and SV callers are following at least the GT and the type column...

Thanks
Fritz

**Comment by Tintest** [comment]
Thank you for your answer.

I did not understand everything about the genotype, is it taken into account by SURVIVOR ? If I replace every genotype by 0/0 or 1/1, is it going to have a different impact?

I totaly understand why you won't do it. Why I don't understand is why the broad institute is using such kind of ".vcf" format ... 

Regards.

**Comment by fritzsedlazeck** [comment]
Oh sorry. So GT does not have an impact on the merge, but on the SUPP_VEC and SUPP=. Here we are just counting SV with 0/1 or 1/1 and not 0/0.  That is the only difference.

Yeah ... that is a very good question especially since broad is part of the VCF standard group. However, as you know, broad is a large place..

Thanks
Fritz

**Comment by Tintest** [comment]
So if I replace ALL of my GT of all the variants of all my .vcf files by 0/1 or 1/1, it should be alright if I want to compare different .vcf files between them ?

Regards.

**Comment by fritzsedlazeck** [comment]
YES. More important are the type and type column.

**Comment by Tintest** [comment]
> 
> 
> YES. More important are the type and type column.

Ok, thank you very much :)

**Comment by wdecoster** [comment]
@Tintest if you would write the conversion of the GATK format to a normal VCF in python I would be happy to accept a PR to add a new subcommand to surpyvor!

**Comment by Tintest** [comment]
It would have been with pleasure, but I think that replacing the genotype with a fake is not a viable solution to integrate into your tool. What I did looks more like DIY solution adapted to my scientific question than a fix of your tool. I think that the integration of the format of GATK4 will come if they ever make their format standard. Do you agree with me ?

**Comment by wdecoster** [comment]
Oh that's okay too. I add things to surpvyor whenever I solve an issue with SV files, but I won't touch GATK for this soon, I think.
